// Reads .md files under src/app/api-docs/content and emits raw.ts with each as
// an escaped template-string export. Runs as a one-shot script: `pnpm gen:docs`.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const contentDir = join(root, 'src/app/api-docs/content');

const ENTRIES = [
  { path: 'detector/README.en.md', export: 'detectorReadmeEn' },
  { path: 'detector/README.ko.md', export: 'detectorReadmeKo' },
  { path: 'detector/DESIGN.en.md', export: 'detectorDesignEn' },
  { path: 'detector/DESIGN.ko.md', export: 'detectorDesignKo' },
  { path: 'rpc/README.en.md',      export: 'rpcReadmeEn' },
  { path: 'rpc/README.ko.md',      export: 'rpcReadmeKo' },
];

function escapeForTemplate(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const out = [
  '// AUTO-GENERATED by scripts/build-docs.mjs — do not edit by hand.',
  '// Source: src/app/api-docs/content/*.md',
  '// Regenerate: `pnpm gen:docs`',
  '',
];

for (const entry of ENTRIES) {
  const md = await readFile(join(contentDir, entry.path), 'utf-8');
  out.push(`export const ${entry.export} = \`${escapeForTemplate(md)}\`;`);
  out.push('');
}

await writeFile(join(contentDir, 'raw.ts'), out.join('\n'), 'utf-8');
console.log(`✓ Wrote ${ENTRIES.length} entries → src/app/api-docs/content/raw.ts`);
