// AUTO-GENERATED by scripts/build-docs.mjs — do not edit by hand.
// Source: src/app/api-docs/content/*.md
// Regenerate: `pnpm gen:docs`

export const detectorReadmeEn = `<p align="center">
  <h1 align="center">solana-sandwich-detector</h1>
  <p align="center">
    A Rust library for detecting same-block and cross-slot sandwich attacks on Solana.<br/>
    Parses swap events from 8 DEXes and identifies frontrun/victim/backrun patterns using sliding-window correlation, precision filters, and AMM-correct victim-loss replay.
  </p>
</p>

<p align="center">
  <strong>English</strong> &middot;
  <a href="README.ko.md">한국어</a>
</p>

<p align="center">
  <a href="https://github.com/SangHyeonKwon/solana-sandwich-detector/actions/workflows/ci.yml"><img src="https://img.shields.io/github/actions/workflow/status/SangHyeonKwon/solana-sandwich-detector/ci.yml?style=for-the-badge&label=CI" alt="CI" /></a>
  <img src="https://img.shields.io/badge/Rust-000000?style=for-the-badge&logo=rust&logoColor=white" alt="Rust" />
  <img src="https://img.shields.io/badge/Solana-9945FF?style=for-the-badge&logo=solana&logoColor=white" alt="Solana" />
  <img src="https://img.shields.io/badge/Tokio-232323?style=for-the-badge&logo=rust&logoColor=white" alt="Tokio" />
  <img src="https://img.shields.io/badge/License-MIT-blue?style=for-the-badge" alt="MIT License" />
</p>

<p align="center">
  <a href="#quick-start">Quick Start</a> &middot;
  <a href="#how-it-works">How It Works</a> &middot;
  <a href="#vigil-integration">Vigil Integration</a> &middot;
  <a href="#use-as-a-library">Library</a> &middot;
  <a href="#scope">Scope</a> &middot;
  <a href="#contributing">Contributing</a>
</p>

---

Sandwich attacks are the most common form of MEV exploitation on Solana. An attacker front-runs a victim's swap, pushes the price, and back-runs to profit — within the same block or across nearby slots.

**solana-sandwich-detector** is a Rust library that turns a stream of Solana blocks into a stream of detected attacks. It supports **same-block detection** (classic single-slot pattern) and **cross-slot window detection** (attacks spanning multiple slots, with Jito bundle provenance, economic feasibility, and victim plausibility filters). AMM-replay enrichment computes the victim's *actual loss* — not just the naive \`amount_out - amount_in\` heuristic. A streaming CLI (\`sandwich-detect\`), an evaluation framework (\`sandwich-eval\`), and a parser-vs-RPC cross-check tool (\`balance-diff\`) ship alongside.

> Powers [Vigil](https://github.com/EarthIsMine/Vigil-RPC) — a Solana MEV transparency platform — as the detection primitive. Validator scoring, persistence, alerting, and dashboards live in Vigil; this repo stays focused on **stream-in → stream-out**. See [Scope](#scope) and [Vigil Integration](#vigil-integration).

### Supported DEXes

| DEX | Swap-event parsing | AMM replay (victim-loss) |
|-----|--------------------|---------------------------|
| Raydium V4 | Direct swaps + CPI | ✅ Constant product |
| Raydium CPMM | Direct swaps + CPI | ✅ Constant product |
| Raydium CLMM | Direct swaps + CPI | ✅ Concentrated, within-tick + cross-tick |
| Orca Whirlpool | Direct swaps + CPI | ✅ Concentrated, within-tick + cross-tick |
| Meteora DLMM | Direct swaps + CPI | ✅ Constant-sum, within-bin + cross-bin |
| Jupiter V6 | Route-through (resolves underlying pool) | ✅ Single-hop dispatch via underlying DEX (multi-hop deferred) |
| Pump.fun | Direct swaps + CPI | ✅ Bonding curve, virtual reserves recovered from \`TradeEvent\` log |
| Phoenix | Direct swaps + CPI | — (CLOB; not yet supported) |

> Adding a new DEX takes ~50 lines for swap parsing; replay support adds another module. See [Contributing](#contributing).

---

## Quick Start

The repo ships with \`sandwich-detect\`, a streaming CLI that wraps the library — useful for smoke-testing, ad-hoc analysis, and piping detections into other tools (Vigil, \`jq\`, a database, your own dashboard). For embedding in your own service, [use the library directly](#use-as-a-library).

\`\`\`bash
# Build
cargo build --release

# Stream new blocks and print detected sandwiches as JSON lines
./target/release/sandwich-detect --rpc $RPC_URL --follow
\`\`\`

Each detected sandwich prints as a JSON line to stdout:

\`\`\`jsonc
{
  "slot": 285012345,
  "attacker": "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
  "frontrun": { "signature": "4vJ9JU1b...", "dex": "raydium_v4", "direction": "buy",  "amount_in": 5000000000, "amount_out": 128934512 },
  "victim":   { "signature": "3kPnR8xz...", "dex": "raydium_v4", "direction": "buy",  "amount_in": 2000000000, "amount_out":  48201100 },
  "backrun":  { "signature": "5tYm2Wqp...", "dex": "raydium_v4", "direction": "sell", "amount_in":  128934512, "amount_out": 5127300000 },
  "pool": "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2",
  "dex": "raydium_v4",
  "victim_loss_lamports": 8423100,
  "attacker_profit": 6210400,
  "price_impact_bps": 142,
  "severity": "medium",
  "confidence": 0.86,
  "confidence_level": "high"
}
\`\`\`

Pipe it anywhere — \`jq\`, a database, an alert system, your own dashboard.

### More examples

\`\`\`bash
# Analyze a specific slot
sandwich-detect --rpc $RPC_URL --slot 285012345

# Scan a range of slots
sandwich-detect --rpc $RPC_URL --range 285012000-285012100

# Cross-slot detection with a 4-slot sliding window
sandwich-detect --rpc $RPC_URL --range 285012000-285012100 --window 4

# Pretty-print for humans
sandwich-detect --rpc $RPC_URL --follow --format pretty

# Scan a range and emit an aggregate economics summary at the end
# (enrichment is on by default; pass --no-enrich to disable)
sandwich-detect --rpc $RPC_URL --range 285012000-285012100 --window 4 --summary
\`\`\`

\`RPC_URL\` can be passed via \`--rpc\` flag or as an environment variable. Pool-state enrichment also uses that RPC by default; set \`--pool-state $OTHER_URL\` (or \`POOL_STATE_RPC\`) to route config fetches elsewhere.

---

## How It Works

The detector emits a \`SandwichAttack\` when three swaps in a pool match a frontrun / victim / backrun pattern: same attacker on the outer two, opposite directions, victim sandwiched between them with a different signer and the same direction as the frontrun. **Same-block detection** handles the classic single-slot pattern; **cross-slot window detection** handles attacks spanning up to W slots, with Jito bundle provenance, economic feasibility, and victim plausibility filters layered on top to produce a composite confidence score.

When a detection fires, **AMM-replay enrichment** recomputes the victim's loss by running the swap through the pool's own math twice — once with the frontrun (the actual world) and once without (the counterfactual world) — and taking the difference. Constant-product pools replay from \`pre/post_token_balances\` in the tx meta directly; concentrated-liquidity AMMs (Whirlpool, Raydium CLMM, DLMM) fetch the pool account's dynamic snapshot via \`getAccountInfo\`; Pump.fun recovers its virtual reserves from the \`TradeEvent\` Anchor log it emits per swap. Replay-correct numbers can flip the rule-based call: a sandwich that looked profitable by \`amount_out − amount_in\` may show an attacker *loss* once the round-trip is replayed in the right token denomination.

Phoenix (CLOB) and multi-hop Jupiter routes are detection-only at v1; the per-DEX heartbeat metric tracks coverage so consumers can see what passed through unenriched.

> **For the methodology in detail** — detection rules table, per-DEX replay primitives, evidence/confidence taxonomy (5-category signal ensemble + Tier 3 economic signals), and the validation strategy (golden corpora + property-based + real-mainnet capture as fixture) — see [DESIGN.md](DESIGN.md).

---

## Vigil Integration

This repo is the upstream detection primitive for [Vigil](https://github.com/EarthIsMine/Vigil-RPC). The contract surface is stable enough for Vigil's BE/FE to ship today; the four pieces below are what a downstream consumer wires against.

### 1. JSONL stream contract

\`sandwich-detect\` emits three line shapes on stdout, all newline-delimited JSON. A consumer dispatches on a discriminator:

\`\`\`jsonc
// Header — emitted once at startup.
{ "_header": true, "schema_version": "vigil-v1", "tool_version": "0.x.y", "started_at_ms": 1730000000000 }

// Heartbeat — every 30s while running. Includes enrichment metric snapshot,
// bucketed per \`DexType\` so ops can tell which DEX's 5-array fetch window
// is under-fetching. All 8 DexType keys are always present (zero-filled).
// \`_heartbeat\` itself is the unix-ms timestamp (not a bool).
{ "_heartbeat": 1730000030000, "metrics": {
    "raydium_v4":     { "enriched": 90, "unsupported_dex": 0, "config_unavailable": 1,
                        "reserves_missing": 0, "replay_failed": 0, "cross_boundary_unsupported": 0 },
    "orca_whirlpool": { "enriched": 32, "unsupported_dex": 0, "config_unavailable": 1,
                        "reserves_missing": 1, "replay_failed": 0, "cross_boundary_unsupported": 3 },
    "meteora_dlmm":   { "enriched": 20, "unsupported_dex": 0, "config_unavailable": 1,
                        "reserves_missing": 0, "replay_failed": 0, "cross_boundary_unsupported": 1 },
    /* raydium_clmm, raydium_cpmm, jupiter_v6, pump_fun, phoenix elided */ } }

// SandwichAttack — one per detection. Full schema in vigil-v1.json.
{ "slot": 285012345, "attacker": "...", "frontrun": {...}, "victim": {...}, ... }
\`\`\`

### 2. Schema + TypeScript types

| File | Purpose |
|------|---------|
| \`crates/swap-events/schema/vigil-v1.json\` | Canonical JSON Schema for \`SandwichAttack\`. Generated by \`cargo run -p swap-events --bin gen-schema\`. |
| \`contrib/vigil-types.ts\` | Hand-tuned TS interfaces matching the schema. Includes \`parseDetectorLine()\` discriminator + BigInt guidance for u128 fields (sqrt_price, liquidity, bin_price). |
| \`swap_events::SCHEMA_VERSION\` | Rust constant \`"vigil-v1"\`. Bumped on breaking schema changes. |

### 3. BE-friendly Rust helpers

\`\`\`rust
// One-shot conversion: SandwichAttack → MevReceipt (per-victim row for Vigil's \`mev_receipt\` table).
let receipt = MevReceipt::from_attack(&attack);

// Idempotent: derives Vigil-shaped fields (attack_signature, attack_type, confidence_level,
// victim_signer/amount_*, receipts vec) from raw detector output. Caller can pre-set any
// field to override; finalize() preserves what's already non-None.
attack.finalize_for_vigil();
\`\`\`

\`finalize_for_vigil()\` intentionally **does not set \`severity\`** — that needs pool-TVL context the BE holds. Same for USD pricing on receipts. Other Vigil columns (slot leader, validator identity) are populated by Tier 2 enrichment when configured.

### 4. NestJS consumer example

\`contrib/vigil-service.example.ts\` ships a complete NestJS service: spawns \`sandwich-detect --follow\`, reads stdout via readline, dispatches header/heartbeat/attack lines, handles graceful restart, and stubs out DB writes / WebSocket broadcasts. Drop-in starting point.

---

## Use as a Library

Add to your \`Cargo.toml\`:

\`\`\`toml
[dependencies]
sandwich-detector = { git = "https://github.com/SangHyeonKwon/solana-sandwich-detector" }
\`\`\`

### Same-block detection

\`\`\`rust
use sandwich_detector::{detector, dex, source::{BlockSource, rpc::RpcBlockSource}};

let source = RpcBlockSource::new("https://api.mainnet-beta.solana.com");
let parsers = dex::all_parsers();

let block = source.get_block(slot).await?;
let swaps: Vec<_> = block.transactions.iter()
    .flat_map(|tx| dex::extract_swaps(tx, &parsers))
    .collect();

let sandwiches = detector::detect_sandwiches(slot, &swaps);
\`\`\`

### Cross-slot window detection

\`\`\`rust
use sandwich_detector::window::{FilteredWindowDetector, WindowDetector};

let mut detector = FilteredWindowDetector::new(4); // 4-slot window

// Feed slots in order
for (slot, swaps) in blocks_stream {
    let attacks = detector.ingest_slot(slot, swaps);
    for attack in &attacks {
        println!("Sandwich: confidence={:.2}", attack.confidence.unwrap_or(0.0));
    }
}

// Flush remaining buffered detections
let remaining = detector.flush();
\`\`\`

### Key types

| Type | Description |
|------|-------------|
| \`SwapEvent\` | A single parsed swap (signer, pool, direction, amounts) |
| \`SandwichAttack\` | A detected sandwich (frontrun + victim + backrun + confidence + replay) |
| \`BlockSource\` | Trait — plug in your own block fetcher (RPC, gRPC, WebSocket) |
| \`DexParser\` | Trait — add support for any DEX in ~50 lines |
| \`WindowDetector\` | Trait — cross-slot detection with sliding window |
| \`FilteredWindowDetector\` | Production detector with 3 precision filters + confidence scoring |
| \`FilterConfig\` | Configurable thresholds (min profit, victim ratio, confidence) |
| \`BundleLookup\` | Trait — inject Jito bundle data for provenance classification |
| \`PoolStateLookup\` | Trait — config + dynamic state + tick/bin array fetches for AMM replay |
| \`AccountFetcher\` | Trait — slot-aware account fetch surface for archival providers |
| \`MevReceipt\` | Per-victim row shape for downstream persistence |

---

## Project Structure

\`\`\`
crates/
  swap-events/           Swap event types, DEX parsers, block sources
                         + JSON schema (vigil-v1.json) + gen-schema bin
  detector-sameblock/    Same-block sandwich detection
  detector-window/       Cross-slot window detector + precision filters
  pool-state/            AMM math + pool-state enrichment + replay diffs
                         (constant product / Whirlpool / DLMM)
  detector/              Facade crate (re-exports for backward compatibility)
  cli/                   CLI binaries (sandwich-detect, balance-diff)
  eval/                  Evaluation framework + economic aggregates

contrib/
  vigil-types.ts         TS interfaces matching vigil-v1.json
  vigil-service.example.ts  NestJS consumer driver
\`\`\`

---

## Scope

This library covers **detection over a stream of blocks** — both same-block and cross-slot patterns, plus AMM-correct victim-loss replay. Anything stateful, opinionated, or product-shaped is out of scope and lives in [Vigil](https://github.com/EarthIsMine/Vigil-RPC) instead.

**In scope** (PRs welcome):

- New DEX parsers (Lifinity, Marinade, Sanctum, ...)
- New \`BlockSource\` implementations (Yellowstone gRPC, Geyser, fixture file, WebSocket)
- Same-block and cross-slot detection accuracy fixes
- Confidence scoring and filter tuning
- Jito bundle integration improvements
- Eval framework improvements (metrics, labeling tools)
- Pool-state coverage for more AMMs (Raydium CLMM, Lifinity, ...)
- Mainnet test fixtures
- Performance: allocation reduction, parallelism, batching
- API ergonomics, documentation, examples
- CLI flags that stay within "stream in → stream out"

**Out of scope** (these belong in a downstream consumer like Vigil):

- Validator-aware or leader-aware analysis
- Multi-hop Jupiter route resolution
- Wash-trading false-positive filters
- ML-based confidence scoring
- Persistence (databases, file stores, indexers)
- Alerting (webhooks, Slack, Discord, email, ...)
- Metrics endpoints (Prometheus, OpenTelemetry, ...)
- Web UIs, dashboards, visualizations
- Stateful services of any kind built into the CLI

The rule of thumb: **"compute over a stream"** stays here, **"state, output, presentation"** goes downstream.

---

## Contributing

PRs welcome. Here's where help is most valuable:

- **Add a DEX parser** — implement \`DexParser\` for a new protocol (Lifinity, Marinade, Sanctum, ...)
- **Add test fixtures** — capture mainnet blocks with confirmed sandwiches under \`fixtures/\`
- **Improve detection** — edge cases, cross-slot accuracy, confidence tuning
- **Eval framework** — add labeled datasets, improve metrics, new evaluation modes
- **Add block sources** — gRPC (Yellowstone), WebSocket subscriptions
- **Pool-state coverage** — add a new AMM's replay (Raydium CLMM next on the list)

\`\`\`bash
# Run tests
cargo test --workspace

# Check everything compiles
cargo check --workspace

# Regenerate the Vigil schema (run before committing schema changes)
cargo run -p swap-events --bin gen-schema > crates/swap-events/schema/vigil-v1.json
\`\`\`

---

## Reproduce the numbers

The measurement flow is deterministic — given a slot range and RPC endpoint, anyone gets the same output. To reproduce a run:

\`\`\`bash
# Raw detections as JSONL (one per line). Use this for any multi-day run —
# the scanner doesn't buffer, it just streams to disk.
sandwich-detect \\
    --rpc $RPC_URL \\
    --range <START>-<END> \\
    --window 4 \\
    --pool-state $RPC_URL \\
  > detections.jsonl

# Aggregate the JSONL into the headline report (human-readable or JSON).
sandwich-eval summarize --input detections.jsonl > report.txt
sandwich-eval summarize --input detections.jsonl --json > report.json
\`\`\`

For short runs the scanner can also emit the report itself by passing \`--summary\`; the aggregation runs in-memory, fine up to a few hundred MB of detections but not for multi-day scans.

The summary includes total victim loss (quote-token smallest unit), unique attackers/victims/pools, per-DEX breakdown, top attackers by extracted value, and a *reclassification rate* — the share of sandwiches the naive rule-based profit flags as profitable but AMM replay shows to be losing money. That reclassification is the signal that makes pool-state enrichment worth running.

Results for specific slot ranges (and the raw JSONL used to produce them) will be published alongside write-ups; see [Vigil](https://github.com/EarthIsMine/Vigil-RPC) for ongoing runs.

---

## License

MIT
`;

export const detectorReadmeKo = `<p align="center">
  <h1 align="center">solana-sandwich-detector</h1>
  <p align="center">
    솔라나의 same-block / cross-slot 샌드위치 공격을 탐지하는 Rust 라이브러리.<br/>
    8개 DEX의 swap 이벤트를 파싱하고, 슬라이딩 윈도우 상관·정밀 필터·AMM 정확 재연(replay)으로 frontrun/victim/backrun 패턴을 식별합니다.
  </p>
</p>

<p align="center">
  <a href="README.md">English</a> &middot;
  <strong>한국어</strong>
</p>

<p align="center">
  <a href="https://github.com/SangHyeonKwon/solana-sandwich-detector/actions/workflows/ci.yml"><img src="https://img.shields.io/github/actions/workflow/status/SangHyeonKwon/solana-sandwich-detector/ci.yml?style=for-the-badge&label=CI" alt="CI" /></a>
  <img src="https://img.shields.io/badge/Rust-000000?style=for-the-badge&logo=rust&logoColor=white" alt="Rust" />
  <img src="https://img.shields.io/badge/Solana-9945FF?style=for-the-badge&logo=solana&logoColor=white" alt="Solana" />
  <img src="https://img.shields.io/badge/Tokio-232323?style=for-the-badge&logo=rust&logoColor=white" alt="Tokio" />
  <img src="https://img.shields.io/badge/License-MIT-blue?style=for-the-badge" alt="MIT License" />
</p>

<p align="center">
  <a href="#빠른-시작">빠른 시작</a> &middot;
  <a href="#동작-원리">동작 원리</a> &middot;
  <a href="#vigil-통합">Vigil 통합</a> &middot;
  <a href="#라이브러리로-사용">라이브러리</a> &middot;
  <a href="#범위">범위</a> &middot;
  <a href="#기여">기여</a>
</p>

---

샌드위치 공격은 솔라나에서 가장 흔한 MEV 추출 패턴입니다. 공격자는 피해자의 swap을 앞질러 frontrun으로 가격을 밀고, 뒤이은 backrun으로 차익을 회수합니다 — 같은 블록 안에서, 또는 인접한 슬롯에 걸쳐서.

**solana-sandwich-detector**는 솔라나 블록 스트림을 탐지된 공격의 스트림으로 변환하는 Rust 라이브러리입니다. **same-block 탐지**(고전적 단일 슬롯 패턴)와 **cross-slot 윈도우 탐지**(여러 슬롯에 걸친 공격, Jito 번들 출처·경제적 타당성·피해자 그럴듯함 필터 포함)를 모두 지원합니다. AMM 재연 enrichment는 단순 \`amount_out - amount_in\` 휴리스틱이 아닌 *실제 victim loss*를 계산합니다. 스트리밍 CLI(\`sandwich-detect\`), 평가 프레임워크(\`sandwich-eval\`), parser-vs-RPC 교차검증 도구(\`balance-diff\`)가 함께 제공됩니다.

> [Vigil](https://github.com/EarthIsMine/Vigil-RPC) — 솔라나 MEV 투명성 플랫폼 — 의 탐지 primitive로 사용됩니다. 검증인 점수·영속성·알림·대시보드는 Vigil에 살고, 이 저장소는 **stream-in → stream-out**에 집중합니다. [범위](#범위) 및 [Vigil 통합](#vigil-통합) 참조.

### 지원 DEX

| DEX | Swap 이벤트 파싱 | AMM 재연 (victim loss) |
|-----|------------------|------------------------|
| Raydium V4 | Direct + CPI | ✅ Constant product |
| Raydium CPMM | Direct + CPI | ✅ Constant product |
| Raydium CLMM | Direct + CPI | ✅ Concentrated, within-tick + cross-tick |
| Orca Whirlpool | Direct + CPI | ✅ Concentrated, within-tick + cross-tick |
| Meteora DLMM | Direct + CPI | ✅ Constant-sum, within-bin + cross-bin |
| Jupiter V6 | Route-through (underlying pool 해석) | ✅ Single-hop은 underlying DEX로 dispatch (multi-hop 미지원) |
| Pump.fun | Direct + CPI | ✅ Bonding curve, virtual reserves를 \`TradeEvent\` log에서 복원 |
| Phoenix | Direct + CPI | — (CLOB; 미지원) |

> 새 DEX 추가는 swap 파싱이 ~50줄, replay 지원은 별도 모듈. [기여](#기여) 참조.

---

## 빠른 시작

\`sandwich-detect\`은 라이브러리를 감싼 스트리밍 CLI입니다 — 스모크 테스트, 임시 분석, 다른 도구(Vigil, \`jq\`, DB, 자체 대시보드)로 파이핑할 때 유용합니다. 자체 서비스에 임베드하려면 [라이브러리를 직접 사용](#라이브러리로-사용)하세요.

\`\`\`bash
# 빌드
cargo build --release

# 신규 블록 스트리밍 + 탐지된 샌드위치를 JSON 라인으로 출력
./target/release/sandwich-detect --rpc $RPC_URL --follow
\`\`\`

탐지된 샌드위치는 stdout에 JSON 라인으로 찍힙니다:

\`\`\`jsonc
{
  "slot": 285012345,
  "attacker": "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
  "frontrun": { "signature": "4vJ9JU1b...", "dex": "raydium_v4", "direction": "buy",  "amount_in": 5000000000, "amount_out": 128934512 },
  "victim":   { "signature": "3kPnR8xz...", "dex": "raydium_v4", "direction": "buy",  "amount_in": 2000000000, "amount_out":  48201100 },
  "backrun":  { "signature": "5tYm2Wqp...", "dex": "raydium_v4", "direction": "sell", "amount_in":  128934512, "amount_out": 5127300000 },
  "pool": "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2",
  "dex": "raydium_v4",
  "victim_loss_lamports": 8423100,
  "attacker_profit": 6210400,
  "price_impact_bps": 142,
  "severity": "medium",
  "confidence": 0.86,
  "confidence_level": "high"
}
\`\`\`

\`jq\`, DB, 알림 시스템, 자체 대시보드 — 어디로든 파이핑 가능.

### 추가 예시

\`\`\`bash
# 특정 슬롯 분석
sandwich-detect --rpc $RPC_URL --slot 285012345

# 슬롯 범위 스캔
sandwich-detect --rpc $RPC_URL --range 285012000-285012100

# 4-슬롯 슬라이딩 윈도우로 cross-slot 탐지
sandwich-detect --rpc $RPC_URL --range 285012000-285012100 --window 4

# 사람이 읽기 좋게 pretty-print
sandwich-detect --rpc $RPC_URL --follow --format pretty

# 범위 스캔 + 끝에 경제 요약 출력
# (enrichment는 기본 ON; --no-enrich로 끔)
sandwich-detect --rpc $RPC_URL --range 285012000-285012100 --window 4 --summary
\`\`\`

\`RPC_URL\`은 \`--rpc\` 플래그 또는 환경 변수로 전달 가능. Pool-state enrichment도 같은 RPC를 기본 사용; \`--pool-state $OTHER_URL\` (혹은 \`POOL_STATE_RPC\`)로 config fetch만 별도 라우팅 가능.

---

## 동작 원리

탐지기는 한 pool 안에서 세 swap이 frontrun / victim / backrun 패턴을 이룰 때 \`SandwichAttack\` 을 emit합니다 — 외곽 두 leg는 같은 attacker, 반대 방향, 가운데 victim은 다른 signer + frontrun과 같은 방향. **Same-block 탐지**가 단일 슬롯 내 고전 패턴을, **cross-slot 윈도우 탐지**가 W 슬롯에 걸친 공격을 처리합니다. cross-slot 쪽은 Jito 번들 출처 / 경제적 타당성 / 피해자 그럴듯함 세 가지 정밀 필터를 layered해 합성 신뢰도 점수를 산출합니다.

탐지가 발화하면 **AMM 재연 enrichment** 가 victim의 손실을 pool 자체 수학으로 두 번 — frontrun 적용 (실제) + 미적용 (반사실) — 재연하고 그 차로 계산합니다. Constant-product pool은 tx 메타의 \`pre/post_token_balances\` 만으로 재연; concentrated-liquidity AMM (Whirlpool, Raydium CLMM, DLMM)은 pool 계정의 동적 스냅샷을 \`getAccountInfo\` 로 가져옴; Pump.fun 은 swap마다 emit되는 \`TradeEvent\` Anchor log 에서 가상 reserves 를 복원합니다. 재연 정확한 수치는 규칙 기반 판정을 뒤집을 수 있음 — \`amount_out − amount_in\` 으로는 수익으로 보이는 sandwich 가, 토큰 단위 정렬해 round-trip 재연하면 attacker 손실로 드러나는 케이스가 있음.

Phoenix(CLOB)와 multi-hop Jupiter route 는 v1 에서 detection-only; 미수신 enrichment 가시성을 위해 per-DEX heartbeat 메트릭으로 추적됩니다.

> **자세한 방법론** — 탐지 규칙 표, DEX별 replay primitive, evidence/confidence 분류 (5-카테고리 신호 ensemble + Tier 3 경제 신호), 검증 전략 (golden/adversarial corpus + property-based + real-mainnet capture as fixture) — 은 [DESIGN.ko.md](DESIGN.ko.md) 참조.

---

## Vigil 통합

이 저장소는 [Vigil](https://github.com/EarthIsMine/Vigil-RPC)의 상위(upstream) 탐지 primitive입니다. contract surface는 Vigil의 BE/FE가 *지금 출시 가능*할 만큼 안정적이며, 다운스트림 소비자가 결합해야 할 네 조각은 다음과 같습니다.

### 1. JSONL 스트림 contract

\`sandwich-detect\`은 stdout으로 세 가지 라인 형태를 newline-delimited JSON으로 emit합니다. 소비자는 discriminator로 분기:

\`\`\`jsonc
// Header — 시작 시 한 번 emit.
{ "_header": true, "schema_version": "vigil-v1", "tool_version": "0.x.y", "started_at_ms": 1730000000000 }

// Heartbeat — 실행 중 30초마다. \`DexType\`별로 버킷팅된 enrichment 메트릭 스냅샷 포함.
// 어느 DEX의 5-array fetch window가 under-fetch 중인지 ops가 바로 식별 가능.
// 8개 DexType 키는 항상 모두 존재 (0으로 채워져 있을 수 있음).
// \`_heartbeat\` 자체가 unix-ms 타임스탬프 (boolean 아님).
{ "_heartbeat": 1730000030000, "metrics": {
    "raydium_v4":     { "enriched": 90, "unsupported_dex": 0, "config_unavailable": 1,
                        "reserves_missing": 0, "replay_failed": 0, "cross_boundary_unsupported": 0 },
    "orca_whirlpool": { "enriched": 32, "unsupported_dex": 0, "config_unavailable": 1,
                        "reserves_missing": 1, "replay_failed": 0, "cross_boundary_unsupported": 3 },
    "meteora_dlmm":   { "enriched": 20, "unsupported_dex": 0, "config_unavailable": 1,
                        "reserves_missing": 0, "replay_failed": 0, "cross_boundary_unsupported": 1 },
    /* raydium_clmm, raydium_cpmm, jupiter_v6, pump_fun, phoenix 생략 */ } }

// SandwichAttack — 탐지당 1개. 전체 스키마는 vigil-v1.json.
{ "slot": 285012345, "attacker": "...", "frontrun": {...}, "victim": {...}, ... }
\`\`\`

### 2. Schema + TypeScript 타입

| 파일 | 용도 |
|------|------|
| \`crates/swap-events/schema/vigil-v1.json\` | \`SandwichAttack\`의 정규 JSON Schema. \`cargo run -p swap-events --bin gen-schema\`로 재생성. |
| \`contrib/vigil-types.ts\` | 스키마와 매칭되는 손튜닝된 TS 인터페이스. \`parseDetectorLine()\` discriminator + u128 필드(sqrt_price, liquidity, bin_price)에 대한 BigInt 가이드. |
| \`swap_events::SCHEMA_VERSION\` | Rust 상수 \`"vigil-v1"\`. 호환성 깨짐(breaking) 시 bump. |

### 3. BE 친화적 Rust 헬퍼

\`\`\`rust
// 일회성 변환: SandwichAttack → MevReceipt (Vigil의 \`mev_receipt\` 테이블용 피해자별 행).
let receipt = MevReceipt::from_attack(&attack);

// 멱등(idempotent): 원시 detector 출력으로부터 Vigil 모양의 필드(attack_signature,
// attack_type, confidence_level, victim_signer/amount_*, receipts vec)를 도출.
// 호출자가 어떤 필드든 미리 설정해서 오버라이드 가능; finalize()는 이미 None이 아닌 값을 보존.
attack.finalize_for_vigil();
\`\`\`

\`finalize_for_vigil()\`은 의도적으로 **\`severity\`를 설정하지 않습니다** — pool-TVL 컨텍스트가 필요하고 그건 BE가 보유. 영수증의 USD 가격도 동일. 다른 Vigil 컬럼(slot leader, validator identity)은 Tier 2 enrichment가 구성되어 있을 때 채워집니다.

### 4. NestJS 소비자 예시

\`contrib/vigil-service.example.ts\`는 완성된 NestJS 서비스를 제공합니다: \`sandwich-detect --follow\` 스폰, readline으로 stdout 읽기, header/heartbeat/attack 라인 분기, graceful 재시작 처리, DB write/WebSocket broadcast 자리표시자 포함. 즉시 사용 가능한 시작점.

---

## 라이브러리로 사용

\`Cargo.toml\`에 추가:

\`\`\`toml
[dependencies]
sandwich-detector = { git = "https://github.com/SangHyeonKwon/solana-sandwich-detector" }
\`\`\`

### Same-block 탐지

\`\`\`rust
use sandwich_detector::{detector, dex, source::{BlockSource, rpc::RpcBlockSource}};

let source = RpcBlockSource::new("https://api.mainnet-beta.solana.com");
let parsers = dex::all_parsers();

let block = source.get_block(slot).await?;
let swaps: Vec<_> = block.transactions.iter()
    .flat_map(|tx| dex::extract_swaps(tx, &parsers))
    .collect();

let sandwiches = detector::detect_sandwiches(slot, &swaps);
\`\`\`

### Cross-slot 윈도우 탐지

\`\`\`rust
use sandwich_detector::window::{FilteredWindowDetector, WindowDetector};

let mut detector = FilteredWindowDetector::new(4); // 4-슬롯 윈도우

// 슬롯을 순서대로 공급
for (slot, swaps) in blocks_stream {
    let attacks = detector.ingest_slot(slot, swaps);
    for attack in &attacks {
        println!("Sandwich: confidence={:.2}", attack.confidence.unwrap_or(0.0));
    }
}

// 버퍼에 남은 탐지 flush
let remaining = detector.flush();
\`\`\`

### 핵심 타입

| 타입 | 설명 |
|------|------|
| \`SwapEvent\` | 단일 파싱된 swap (signer, pool, direction, amounts) |
| \`SandwichAttack\` | 탐지된 샌드위치 (frontrun + victim + backrun + confidence + replay) |
| \`BlockSource\` | Trait — 자체 block fetcher 끼우기 (RPC, gRPC, WebSocket) |
| \`DexParser\` | Trait — 임의의 DEX 지원을 ~50줄에 추가 |
| \`WindowDetector\` | Trait — 슬라이딩 윈도우 cross-slot 탐지 |
| \`FilteredWindowDetector\` | 3개 정밀 필터 + 신뢰도 채점이 있는 프로덕션 탐지기 |
| \`FilterConfig\` | 설정 가능한 임계치 (min profit, victim ratio, confidence) |
| \`BundleLookup\` | Trait — 출처 분류용 Jito 번들 데이터 주입 |
| \`PoolStateLookup\` | Trait — AMM 재연용 config + 동적 상태 + tick/bin array fetch |
| \`AccountFetcher\` | Trait — archival provider용 슬롯 인지 account fetch surface |
| \`MevReceipt\` | 다운스트림 영속화용 피해자별 행 모양 |

---

## 프로젝트 구조

\`\`\`
crates/
  swap-events/           Swap 이벤트 타입, DEX 파서, 블록 소스
                         + JSON 스키마(vigil-v1.json) + gen-schema bin
  detector-sameblock/    Same-block 샌드위치 탐지
  detector-window/       Cross-slot 윈도우 탐지기 + 정밀 필터
  pool-state/            AMM 수학 + pool-state enrichment + replay diff
                         (constant product / Whirlpool / DLMM)
  detector/              파사드 크레이트 (하위 호환성용 re-export)
  cli/                   CLI 바이너리 (sandwich-detect, balance-diff)
  eval/                  평가 프레임워크 + 경제 집계

contrib/
  vigil-types.ts         vigil-v1.json과 일치하는 TS 인터페이스
  vigil-service.example.ts  NestJS 소비자 드라이버
\`\`\`

---

## 범위

이 라이브러리는 **블록 스트림에 대한 탐지** — same-block과 cross-slot 패턴, 그리고 AMM 정확 victim-loss 재연 — 을 다룹니다. 상태(stateful)·견해(opinionated)·제품 형태인 것은 범위 밖이며 다운스트림 소비자인 [Vigil](https://github.com/EarthIsMine/Vigil-RPC)에 살게 됩니다.

**범위 안** (PR 환영):

- 새 DEX 파서 (Lifinity, Marinade, Sanctum, ...)
- 새 \`BlockSource\` 구현 (Yellowstone gRPC, Geyser, fixture file, WebSocket)
- Same-block / cross-slot 탐지 정확도 개선
- 신뢰도 채점과 필터 튜닝
- Jito 번들 통합 개선
- 평가 프레임워크 개선 (메트릭, 라벨링 도구)
- 더 많은 AMM의 pool-state 커버리지 (Raydium CLMM, Lifinity, ...)
- 메인넷 테스트 fixture
- 성능: 할당 감소, 병렬화, 배치
- API 인체공학·문서·예시
- "stream in → stream out" 안에 머무는 CLI 플래그

**범위 밖** (Vigil 같은 다운스트림 소비자에 속함):

- 검증인 인지 / 리더 인지 분석
- 멀티홉 Jupiter 라우트 해석
- Wash-trading 거짓양성 필터
- ML 기반 신뢰도 채점
- 영속성 (DB, 파일 스토어, 인덱서)
- 알림 (webhook, Slack, Discord, 이메일, ...)
- 메트릭 엔드포인트 (Prometheus, OpenTelemetry, ...)
- 웹 UI, 대시보드, 시각화
- CLI에 박힌 어떤 stateful 서비스든

원칙: **"스트림 위 계산"**은 여기에, **"상태·출력·표현"**은 다운스트림에.

---

## 기여

PR 환영. 도움이 가장 가치 있는 곳:

- **DEX 파서 추가** — 새 프로토콜에 \`DexParser\` 구현 (Lifinity, Marinade, Sanctum, ...)
- **테스트 fixture 추가** — 확인된 샌드위치가 있는 메인넷 블록을 \`fixtures/\`에 캡처
- **탐지 개선** — 엣지 케이스, cross-slot 정확도, 신뢰도 튜닝
- **평가 프레임워크** — 라벨링 데이터셋 추가, 메트릭 개선, 새 평가 모드
- **블록 소스 추가** — gRPC (Yellowstone), WebSocket 구독
- **Pool-state 커버리지** — 새 AMM의 replay 추가 (다음 후보: Raydium CLMM)

\`\`\`bash
# 테스트 실행
cargo test --workspace

# 전체 컴파일 확인
cargo check --workspace

# Vigil 스키마 재생성 (스키마 변경 commit 전에 실행)
cargo run -p swap-events --bin gen-schema > crates/swap-events/schema/vigil-v1.json
\`\`\`

---

## 수치 재현

측정 흐름은 결정론적입니다 — 슬롯 범위와 RPC 엔드포인트가 같으면 누가 돌려도 같은 출력. 실행 재현법:

\`\`\`bash
# 원시 탐지를 JSONL로 (한 줄당 하나). 다일(多日) 실행은 이걸 사용 —
# 스캐너는 버퍼링 안 하고 그대로 디스크에 스트리밍.
sandwich-detect \\
    --rpc $RPC_URL \\
    --range <START>-<END> \\
    --window 4 \\
    --pool-state $RPC_URL \\
  > detections.jsonl

# JSONL을 메인 리포트(사람용 또는 JSON)로 집계.
sandwich-eval summarize --input detections.jsonl > report.txt
sandwich-eval summarize --input detections.jsonl --json > report.json
\`\`\`

짧은 실행은 스캐너 자체에 \`--summary\`를 붙여 리포트를 emit할 수도 있습니다; 인메모리 집계라 수백 MB까지는 OK이지만 다일 스캔에는 부적합.

요약은 총 victim loss(quote 토큰 최소 단위), 고유 attacker/victim/pool 수, DEX별 분해, 추출 가치 기준 상위 attacker, 그리고 *재분류율* — 단순 규칙 기반 이익 휴리스틱이 흑자라고 표시하지만 AMM 재연 결과 적자인 샌드위치의 비율 — 을 포함합니다. 이 재분류율이 pool-state enrichment를 돌릴 가치를 만드는 신호입니다.

특정 슬롯 범위에 대한 결과(와 그 raw JSONL)는 글과 함께 게시됩니다; 진행 중인 실행은 [Vigil](https://github.com/EarthIsMine/Vigil-RPC) 참조.

---

## 라이선스

MIT
`;

export const detectorDesignEn = `# Design

<p align="center">
  <strong>English</strong> &middot;
  <a href="DESIGN.ko.md">한국어</a>
</p>

This document describes how the detector works: its detection model, AMM-replay
enrichment, evidence/confidence taxonomy, and validation methodology. The
[README](README.md) covers install, CLI usage, and the Vigil integration
contract; this is for readers who want to know *why* a given detection fires
(or doesn't) and what guarantees the numbers carry.

## 1. Detection model

A sandwich is three swaps in two participants in two roles. The detector reduces
this to a structural pattern over a stream of \`SwapEvent\`s, then layers
precision filters and economic enrichment on top.

### 1.1 Same-block detection

\`\`\`
Block (slot N)
 |
 +-- Parse transactions  -->  Extract swap events per DEX
 |                            (instruction discriminator + token balance deltas)
 |
 +-- Group by pool
 |
 +-- Detect pattern:
       tx[i]  attacker BUYS   -+
       tx[j]  victim   BUYS    +-- same pool, same direction
       tx[k]  attacker SELLS  -+   opposite direction, same signer as tx[i]
\`\`\`

Implementation: \`crates/detector-sameblock/src/detector.rs\`. Operates on a
single block's swap events; no cross-slot state.

### 1.2 Cross-slot window detection

\`\`\`
Slot N:    attacker BUYS in pool P     (frontrun)
Slot N+1:  victim BUYS in pool P       (same direction as frontrun)
Slot N+2:  attacker SELLS in pool P    (backrun -- opposite direction)
\`\`\`

\`FilteredWindowDetector\` (\`crates/detector-window/src/pipeline.rs\`) maintains
a per-pool sliding window of \`W\` slots. Within-window candidate triplets are
passed through three precision filters before emission:

1. **Bundle provenance** — Jito bundle co-location, ranked
   \`AtomicBundle > SpanningBundle > TipRace > Organic\`. Same-bundle frontrun
   and backrun mean the attacker paid for atomicity, the strongest provenance
   signal we can read off-chain.
2. **Economic feasibility** — \`backrun.amount_out − frontrun.amount_in > tx fees\`.
   Loose floor; tightened by AMM-replay enrichment downstream.
3. **Victim plausibility** — size-ratio check against the frontrun (a 1-lamport
   "victim" sandwiched between two large legs is almost certainly a routing
   artifact, not a real sandwich) plus a known-attacker exclusion list for
   wallets verified as MM/arb bots.

Each emitted detection carries a \`confidence\` ∈ [0, 1] composite of the three
filters' outputs; the gate threshold lives in the pipeline.

### 1.3 Detection rules (both detectors)

| Condition | Why |
|-----------|-----|
| \`frontrun.signer == backrun.signer\` | Same attacker |
| \`frontrun.direction != backrun.direction\` | Opposite trades (buy then sell) |
| \`victim.direction == frontrun.direction\` | Victim pushes price further |
| \`victim.signer != attacker\` | Different wallet |
| Same pool | Price impact is local to the pool |
| Same slot (same-block) or within W slots (window) | Temporal proximity |

### 1.4 Hybrid parsing

DEX swap events are extracted using a hybrid strategy: instruction
discriminators identify the program and pool address, while pre/post token
balance changes determine swap direction and amounts. The discriminator side
is brittle (Anchor IDL changes), the balance-delta side is brittle (multi-hop
or routed swaps muddle the net delta), so each parser uses both as a
cross-check. See \`crates/swap-events/src/dex/\`.

## 2. AMM-replay enrichment

Rule-based detection answers *"was this a sandwich?"* but not *"how much did
the victim lose?"* — the naive \`backrun.amount_out − frontrun.amount_in\`
heuristic ignores price-impact dynamics and breaks for multi-token pairs. The
\`pool-state\` crate fixes both by replaying each swap through the AMM's own
math:

\`\`\`
state_0   = pool reserves just before the frontrun  (from tx meta)
state_1   = state_0 after frontrun                  (replay)
state_2   = state_1 after victim                    (replay, "actual")
state_2c  = state_0 after victim, no frontrun       (replay, "counterfactual")
victim_loss  = victim_out(state_2c) − victim_out(state_2)
\`\`\`

The counterfactual replay (\`state_2c\`) is what makes the loss number AMM-correct:
it's the output the victim *would have received* in a world where the frontrun
didn't happen, computed from the same pool math the program itself runs.

### 2.1 Per-DEX reserve sources

| AMM family | Reserve source | Replay primitive |
|---|---|---|
| **Constant product** (Raydium V4 / CPMM) | \`pre_token_balances\` / \`post_token_balances\` from tx meta | \`x * y = k\` |
| **Concentrated liquidity** (Whirlpool, Raydium CLMM) | \`getAccountInfo\` on the pool account for the dynamic snapshot (\`sqrt_price\`, \`liquidity\`, current \`tick\`); tick-array PDAs derived | sqrt-price step + cross-tick walk via the V3 TickArray |
| **Discretised liquidity** (Meteora DLMM) | Pool account + bin-array PDAs for active and adjacent bins | Constant-sum within a bin + cross-bin walk via the bitmap |
| **Bonding curve** (Pump.fun) | \`virtual_sol_reserves\` / \`virtual_token_reserves\` recovered from the \`TradeEvent\` Anchor log Pump.fun emits per swap | Bonding-curve formula |
| **Aggregator** (Jupiter V6) | Resolves the underlying DEX from the route, dispatches to that DEX's replay path | Single-hop only at v1.0; multi-hop deferred |

The constant-product and Pump.fun paths need no extra RPC. V3 / DLMM paths need
\`getAccountInfo\` on the pool account; the
[\`AccountFetcher\`](crates/pool-state/src/rpc.rs) trait abstracts the fetch so
archival providers can be plugged in for backfill (no major Solana RPC
currently exposes slot-aware archival account state — \`getAccountInfo\` always
serves latest-confirmed; \`minContextSlot\` is a freshness floor, not a slot pin).

### 2.2 Enriched output

When enrichment succeeds, each \`SandwichAttack\` carries:

- \`victim_loss_lamports\` — AMM-correct, in the quote token's smallest unit
- \`victim_loss_lamports_lower\` / \`_upper\` — confidence interval from per-step
  parser-vs-model residuals
- \`attacker_profit\` — counterfactual attacker gross profit. Can flip the
  rule-based call: a sandwich that looked profitable by \`amount_out − amount_in\`
  may show an attacker *loss* once the round-trip is replayed (the rule-based
  engine over-attributes when token decimals differ across legs).
- \`price_impact_bps\` — frontrun-induced price shift in basis points
- \`severity\` — bucket from the loss-to-pool-TVL ratio
- One of \`amm_replay\` (constant product), \`clmm_replay\` (V3-style: Whirlpool
  and Raydium CLMM share the schema), \`dlmm_replay\` — the per-DEX raw trace.
  A downstream consumer can recompute the loss step-by-step from this trace
  without re-running the detector.

Attacks on unsupported DEXes (Phoenix today; Jupiter routes through unsupported
underlying pools count too) pass through with the enrichment fields set to
\`None\`. Multi-hop Jupiter routes surface as \`cross_boundary_unsupported\` on
the per-DEX heartbeat metric.

## 3. Evidence and confidence

Every detection carries a \`DetectionEvidence\` block (\`crates/swap-events/src/types.rs\`)
that records the structured signals the detector considered. This is the
"audit trail" — a downstream consumer can re-judge the call without re-running
the detector.

### 3.1 Signal taxonomy

Signals are grouped into five orthogonal categories, so a detection that fires
across many categories is more credible than one that scores highly in a
single category.

| Category | Example signals |
|---|---|
| **Structural** | \`OrderingTight\` (front/back tx-index gaps) |
| **Temporal** | \`SameBlock\`, \`CrossSlot { slot_distance }\` |
| **Provenance** | \`Bundle { provenance, bundle_id }\` |
| **Economic** | \`NaiveProfit\`, \`AmmProfit\`, \`VictimLoss\`, \`ReplayConfidence\`, \`InvariantResidual\`, \`ReservesMatchPostState\` |
| **Plausibility** | \`VictimSize\`, \`KnownAttackerVictim\`, \`AuthorityChain\`, \`CounterfactualAttackerProfit\` |

\`ENSEMBLE_CATEGORY_COUNT = 5\` is the denominator for \`ensemble_agreement\`,
the fraction of categories that fired *Pass* on this detection.

### 3.2 Per-signal verdict

Each signal carries a \`SignalVerdict\`:

- **Pass** — evidence *for* the sandwich call. Ships in
  \`--evidence-mode passing\` (default).
- **Fail** — signal computed and points *against* the call. Detection still
  emits if the composite confidence passes the gate; ships only in
  \`--evidence-mode full\` for debugging.
- **Informational** — neutral context (slot distance, AMM intermediates) that
  helps interpretation but doesn't vote.

### 3.3 Tier 3 economic signals

The "Tier 3" signals (\`InvariantResidual\`, \`ReservesMatchPostState\`,
\`CounterfactualAttackerProfit\`) are model-vs-chain consistency checks layered
on top of replay enrichment:

- **\`InvariantResidual { residual_bps, step }\`** — at each replay step, how far
  the replayed reserves drift from \`pre/post_token_balances\` for that step.
  A small residual is the strongest single piece of evidence that the replay
  lined up with chain reality.
- **\`ReservesMatchPostState { passed, divergence_bps }\`** — end-state diff:
  reserves the replay believes the backrun left behind vs the actual
  post-backrun vault balances from the backrun tx's \`post_token_balances\`.
  Threshold \`100 bps\` (\`crates/pool-state/src/diff_test.rs::PASS_THRESHOLD_BPS\`).
- **\`CounterfactualAttackerProfit { profit_real }\`** — replay-derived attacker
  profit. Used to flag rule-based false positives where the attacker actually
  lost SOL on the round-trip; the most useful single signal for triage.

## 4. Limitations

- **CLOB markets (Phoenix)** — sandwich pattern (limit-order placement) does
  not match the frontrun / victim / backrun model the detector is built
  around. Phoenix retains detection-only coverage; v1 deferred enrichment
  indefinitely. See [CHANGELOG.md](CHANGELOG.md) \`[1.0.0]\` *Deferred*.
- **Multi-hop aggregator routes** — Jupiter V6 single-hop pivots to the
  underlying DEX's replay; multi-hop routes surface as
  \`cross_boundary_unsupported\` on the heartbeat metric. The cross-pool
  invariant is non-trivial when intermediate hops touch unsupported pools.
- **Archival pool state** — V3 / DLMM enrichment fetches pool accounts at
  *current* slot. A months-old sandwich corpus replays against the *current*
  pool account, not the slot-of-incident snapshot. End-to-end replay-vs-chain
  validation on historical data needs a Geyser-backed or ledger-replay
  account fetcher; the underlying library functions
  (\`pool_state::compare_clmm_replay_to_archival\`,
  \`diff_attack_against_archival\`) are ready, the fetcher implementation is
  not.
- **Token-2022 transfer fees** — the parser doesn't account for transfer-fee
  hooks; for mints that use them, \`amount_out\` recorded on a \`SandwichAttack\`
  is the pre-hook value.

## 5. Validation methodology

Three layers, each catches a different bug class.

### 5.1 Golden corpus + adversarial corpus

\`crates/eval/tests/{golden,adversarial}\` pin manifests of curated mainnet
sandwiches. Golden = canonical positives; adversarial = curated negatives
(hop swaps, MM activity, validator reorders) that should *not* fire. CI runs
both; a regression in either turns a check red.

### 5.2 Property-based tests

\`crates/pool-state/tests/k_invariant.rs\` and friends use \`proptest\` to assert
AMM invariants hold across random swap inputs (e.g. \`x * y\` is monotone after
a fee-adjusted swap; sqrt-price moves in the input direction). Catches
math-side regressions a fixture set can't, especially on the V3 sqrt-price
primitives where edge cases live in the i128 saturation boundaries.

### 5.3 Real-mainnet capture as fixture

When a parser bug surfaces on mainnet, the fix lands with an inline
base64-encoded mainnet fixture pinned as a regression test. v1.0.0 surfaced
two such cases:

- **Pump.fun \`TradeEvent\` extended payload** (#35) — the on-chain program
  shipped a backwards-compatible upgrade that appended fields, breaking the
  parser's \`data.len() == 113\` strict-equality check. Lesson: parsers
  decoding external Anchor events must use \`data.len() < MIN_PREFIX\` plus
  field-shape guards, never strict equality on length. Fixture pinned in
  \`parses_real_mainnet_pump_fun_trade_event\`.
- **Raydium CLMM pool account index** (#37) — the parser pulled \`accounts[1]\`
  (the \`amm_config\` PDA, 117 bytes, shared across pools by fee tier) instead
  of \`accounts[2]\` (the \`pool_state\`, 1544 bytes), letting the same-block
  detector group unrelated swaps as cross-mint "sandwiches". Fixed by reading
  the correct index plus four unit tests covering top-level / inner-CPI /
  short-account-list cases.

Both bugs slipped past unit tests because the unit tests' synthetic inputs
matched the parser's assumptions; the mainnet capture broke that. Adding the
real bytes (or, for the CLMM case, the real account ordering) as a fixture is
how we keep them caught next time. New parsers and parser changes must ship
with at least one mainnet-capture test.

### 5.4 Mainnet validation runs

For releases, run the binary over a 1k–10k slot mainnet window and inspect
the per-DEX enrichment matrix. Both v1.0.0 hotfixes were caught this way: the
first by the 1k validation that exposed Pump.fun TradeEvent breakage, the
second by the 10k that exposed CLMM cross-mint false positives at a frequency
the 1k sample missed. Larger sample is the right answer when "the unit tests
pass but production is wrong."

## 6. Where to look

| Question | File |
|---|---|
| How are sandwiches detected? | \`crates/detector-sameblock/src/detector.rs\`, \`crates/detector-window/src/pipeline.rs\` |
| How is a swap parsed for DEX X? | \`crates/swap-events/src/dex/<x>.rs\` |
| What's the AMM-replay math for DEX X? | \`crates/pool-state/src/<x>.rs\` |
| What signals does evidence carry? | \`Signal\` enum in \`crates/swap-events/src/types.rs\` |
| Wire format / Vigil contract? | \`crates/swap-events/schema/vigil-v1.json\` (canonical), \`contrib/vigil-types.ts\` (TS mirror) |
| Validation harness? | \`crates/eval/tests/\`, \`crates/pool-state/tests/\` |
`;

export const detectorDesignKo = `# Design

<p align="center">
  <a href="DESIGN.md">English</a> &middot;
  <strong>한국어</strong>
</p>

이 문서는 detector의 동작 방식 — 검출 모델, AMM replay enrichment, evidence/confidence 분류, 검증 방법론 — 을 다룹니다. [README](README.ko.md)는 설치 / CLI 사용 / Vigil 통합 계약을 다루고, 이 문서는 *왜* 특정 detection이 발화하는지 (또는 안 하는지) 와 emit되는 수치들이 어떤 보장을 갖는지를 알고 싶은 독자를 위한 자료입니다.

## 1. 검출 모델

샌드위치는 두 참가자가 두 역할로 행하는 세 swap입니다. Detector는 이걸 \`SwapEvent\` 스트림 위의 구조적 패턴으로 축소한 뒤, 정밀 필터와 경제적 enrichment를 위에 쌓습니다.

### 1.1 Same-block 검출

\`\`\`
Block (slot N)
 |
 +-- 트랜잭션 파싱 -->  DEX별 swap 이벤트 추출
 |                       (instruction discriminator + 토큰 잔액 변화)
 |
 +-- pool 별 그룹화
 |
 +-- 패턴 검출:
       tx[i]  attacker BUYS   -+
       tx[j]  victim   BUYS    +-- 같은 pool, 같은 방향
       tx[k]  attacker SELLS  -+   반대 방향, tx[i]와 같은 signer
\`\`\`

구현: \`crates/detector-sameblock/src/detector.rs\`. 단일 block의 swap 이벤트만 사용; cross-slot 상태 없음.

### 1.2 Cross-slot 윈도우 검출

\`\`\`
Slot N:    pool P 에서 attacker BUYS    (frontrun)
Slot N+1:  pool P 에서 victim   BUYS    (frontrun과 같은 방향)
Slot N+2:  pool P 에서 attacker SELLS   (backrun — 반대 방향)
\`\`\`

\`FilteredWindowDetector\` (\`crates/detector-window/src/pipeline.rs\`) 는 pool별 \`W\` 슬롯 슬라이딩 윈도우를 유지하며, 윈도우 내 후보 triplet에 emit 직전 세 가지 정밀 필터를 적용합니다:

1. **번들 출처 (Bundle provenance)** — Jito 번들 동소성. 우선순위 \`AtomicBundle > SpanningBundle > TipRace > Organic\`. frontrun과 backrun이 같은 번들이라는 건 attacker가 원자성에 비용을 지불했다는 뜻 — 오프체인에서 읽을 수 있는 가장 강한 provenance 신호.
2. **경제적 타당성 (Economic feasibility)** — \`backrun.amount_out − frontrun.amount_in > tx 수수료\`. 느슨한 floor; AMM-replay enrichment가 다음 단계에서 더 조입니다.
3. **피해자 그럴듯함 (Victim plausibility)** — frontrun 대비 size-ratio 검사 (큰 leg 두 개 사이에 1-lamport "victim"이 끼는 건 거의 routing artifact, 진짜 sandwich 아님) + MM/arb bot으로 확인된 known-attacker 제외 리스트.

각 emit detection은 세 필터 결과의 합성으로 \`confidence\` ∈ [0, 1] 을 갖습니다. gate threshold는 pipeline 안에 있음.

### 1.3 검출 규칙 (두 detector 공통)

| 조건 | 이유 |
|------|------|
| \`frontrun.signer == backrun.signer\` | 같은 attacker |
| \`frontrun.direction != backrun.direction\` | 반대 거래 (사고 → 팔고) |
| \`victim.direction == frontrun.direction\` | victim이 가격을 더 밀어줌 |
| \`victim.signer != attacker\` | 다른 지갑 |
| 같은 pool | 가격 영향이 그 pool에 국지적 |
| 같은 slot (same-block) 또는 W 슬롯 내 (window) | 시간적 근접성 |

### 1.4 하이브리드 파싱

DEX swap 이벤트는 하이브리드 전략으로 추출됩니다: instruction discriminator로 프로그램과 pool 주소를 식별하고, pre/post 토큰 잔액 변화로 swap 방향과 금액을 결정합니다. discriminator 쪽은 (Anchor IDL 변경에) 취약하고 잔액 delta 쪽도 (multi-hop / routed swap이 net delta를 흐림) 취약하므로, 각 parser는 둘을 cross-check 로 사용합니다. \`crates/swap-events/src/dex/\` 참조.

## 2. AMM replay enrichment

규칙 기반 검출은 *"이게 sandwich였나?"* 에는 답하지만 *"피해자는 얼마를 잃었나?"* 에는 답하지 못합니다 — 단순 \`backrun.amount_out − frontrun.amount_in\` 휴리스틱은 가격 영향 동학을 무시하고 multi-token 페어에서 깨집니다. \`pool-state\` 크레이트는 각 swap을 AMM 자체 수학으로 replay 해서 둘 다 해결합니다:

\`\`\`
state_0   = frontrun 직전 pool 잔액           (tx 메타에서)
state_1   = state_0 위에 frontrun 적용         (replay)
state_2   = state_1 위에 victim 적용           (replay, "실제")
state_2c  = state_0 위에 victim 적용, frontrun 없이  (replay, "반사실")
victim_loss  = victim_out(state_2c) − victim_out(state_2)
\`\`\`

반사실 replay (\`state_2c\`) 가 손실 수치를 AMM-correct 하게 만드는 핵심 — frontrun 이 없었던 세계에서 victim이 *받았어야 할* 출력을, 프로그램 자체가 돌리는 같은 pool 수학으로 계산합니다.

### 2.1 DEX별 reserves 출처

| AMM 계열 | Reserves 출처 | Replay primitive |
|---|---|---|
| **Constant product** (Raydium V4 / CPMM) | tx 메타의 \`pre_token_balances\` / \`post_token_balances\` | \`x * y = k\` |
| **Concentrated liquidity** (Whirlpool, Raydium CLMM) | pool 계정에 \`getAccountInfo\` 로 동적 스냅샷 (\`sqrt_price\`, \`liquidity\`, 현 \`tick\`); tick-array PDA 도출 | sqrt-price step + V3 TickArray 통한 cross-tick walk |
| **Discretised liquidity** (Meteora DLMM) | pool 계정 + active/인접 bin 의 bin-array PDA | bin 안에서는 constant-sum + bitmap 통한 cross-bin walk |
| **Bonding curve** (Pump.fun) | Pump.fun 이 swap마다 emit 하는 \`TradeEvent\` Anchor log 에서 \`virtual_sol_reserves\` / \`virtual_token_reserves\` 복원 | 본딩 커브 공식 |
| **Aggregator** (Jupiter V6) | route 에서 underlying DEX 결정 후 그 DEX 의 replay path 로 dispatch | v1 에서 single-hop 만; multi-hop 은 defer |

constant-product 와 Pump.fun 경로는 추가 RPC 불필요. V3 / DLMM 경로는 pool 계정에 \`getAccountInfo\` 필요; [\`AccountFetcher\`](crates/pool-state/src/rpc.rs) trait 가 fetch 를 abstraction 해 archival provider 를 끼워 넣을 수 있게 함 (현재 어떤 메이저 Solana RPC 도 슬롯 인지 archival account state 를 노출하지 않음 — \`getAccountInfo\` 는 항상 latest-confirmed 를 반환하고, \`minContextSlot\` 은 freshness floor 일 뿐 슬롯 pin 이 아님).

### 2.2 Enriched 출력

Enrichment 성공 시 각 \`SandwichAttack\` 은 다음을 갖습니다:

- \`victim_loss_lamports\` — AMM-correct, quote 토큰 최소 단위
- \`victim_loss_lamports_lower\` / \`_upper\` — step별 parser-vs-model 잔차에서 도출한 confidence interval
- \`attacker_profit\` — 반사실 attacker 총 이익. 규칙 기반 판정을 뒤집을 수 있음: \`amount_out − amount_in\` 으로는 수익으로 보이는 sandwich 가, round-trip 이 올바른 토큰 단위로 replay 되면 attacker *손실* 로 드러나는 케이스 (leg 별 토큰 decimals 가 다를 때 규칙 기반이 과대 귀속).
- \`price_impact_bps\` — frontrun 이 유발한 가격 변화 (basis points)
- \`severity\` — loss 대비 pool TVL 비율 버킷
- \`amm_replay\` (constant product), \`clmm_replay\` (V3-style: Whirlpool 과 Raydium CLMM 가 schema 공유), \`dlmm_replay\` 중 하나 — DEX별 raw trace. 다운스트림 소비자가 detector 를 다시 돌리지 않고도 step-by-step 으로 loss 를 재계산 가능.

미지원 DEX (현 Phoenix; Jupiter route 가 미지원 underlying pool 거치는 경우 포함) 의 공격은 enrichment 필드들이 \`None\` 인 채 통과됩니다. Multi-hop Jupiter route 는 per-DEX heartbeat 메트릭의 \`cross_boundary_unsupported\` 로 분류됩니다.

## 3. Evidence 와 confidence

모든 detection 은 \`DetectionEvidence\` 블록 (\`crates/swap-events/src/types.rs\`) 을 carry — detector 가 고려한 구조화된 신호의 기록. 이게 "감사 추적" 역할: 다운스트림 소비자가 detector 를 다시 돌리지 않고도 판정을 재평가 가능.

### 3.1 신호 분류

신호는 다섯 개의 직교 카테고리로 그룹화됩니다 — 여러 카테고리에 걸쳐 발화한 detection 이 한 카테고리 안에서만 강하게 발화한 것보다 더 신뢰됩니다.

| Category | 예시 신호 |
|---|---|
| **Structural** | \`OrderingTight\` (front/back tx-index 갭) |
| **Temporal** | \`SameBlock\`, \`CrossSlot { slot_distance }\` |
| **Provenance** | \`Bundle { provenance, bundle_id }\` |
| **Economic** | \`NaiveProfit\`, \`AmmProfit\`, \`VictimLoss\`, \`ReplayConfidence\`, \`InvariantResidual\`, \`ReservesMatchPostState\` |
| **Plausibility** | \`VictimSize\`, \`KnownAttackerVictim\`, \`AuthorityChain\`, \`CounterfactualAttackerProfit\` |

\`ENSEMBLE_CATEGORY_COUNT = 5\` 가 \`ensemble_agreement\` 의 분모 — 이 detection 위에서 Pass 발화한 카테고리의 비율.

### 3.2 신호별 verdict

각 신호는 \`SignalVerdict\` 를 갖습니다:

- **Pass** — sandwich 판정에 *찬성하는* 증거. \`--evidence-mode passing\` (기본) 으로 ship.
- **Fail** — 신호가 계산되었지만 판정에 *반대하는* 방향. 합성 confidence 가 gate 를 통과하면 detection 은 emit; debug 용 \`--evidence-mode full\` 에서만 ship.
- **Informational** — 중립 컨텍스트 (slot 거리, AMM 중간값 등). 해석에 도움되지만 vote 는 안 함.

### 3.3 Tier 3 경제 신호

"Tier 3" 신호 (\`InvariantResidual\`, \`ReservesMatchPostState\`, \`CounterfactualAttackerProfit\`) 는 replay enrichment 위에 layered 된 model-vs-chain 일관성 검사:

- **\`InvariantResidual { residual_bps, step }\`** — 각 replay step 에서 replay 된 reserves 가 그 step 의 \`pre/post_token_balances\` 에서 얼마나 drift 했는지. 작은 잔차는 replay 가 chain 현실과 일치한다는 가장 강한 단일 증거.
- **\`ReservesMatchPostState { passed, divergence_bps }\`** — end-state diff: replay 가 backrun 후라고 믿는 reserves vs backrun tx 의 \`post_token_balances\` 의 실제 vault 잔액. Threshold \`100 bps\` (\`crates/pool-state/src/diff_test.rs::PASS_THRESHOLD_BPS\`).
- **\`CounterfactualAttackerProfit { profit_real }\`** — replay 도출 attacker 이익. round-trip 에서 attacker 가 실제로 SOL 을 잃은 케이스를 규칙 기반 false positive 로 flag 하는 데 사용 — triage 에 가장 유용한 단일 신호.

## 4. 한계

- **CLOB 마켓 (Phoenix)** — sandwich 패턴 (limit-order placement) 이 detector 가 기반한 frontrun / victim / backrun 모델과 mismatch. Phoenix 는 detection-only 커버리지 유지; v1 enrichment 무한 defer. [CHANGELOG.md](CHANGELOG.md) \`[1.0.0]\` *Deferred* 참조.
- **Multi-hop aggregator route** — Jupiter V6 single-hop 은 underlying DEX replay 로 pivot; multi-hop 은 heartbeat 메트릭의 \`cross_boundary_unsupported\` 로 surface. 중간 hop 이 미지원 pool 을 거칠 때 cross-pool 불변량이 비자명.
- **Archival pool state** — V3 / DLMM enrichment 는 pool 계정을 *현재* slot 에서 fetch. 수개월 된 sandwich 코퍼스를 replay 하면 *현재* pool 계정에 대해 돌아감, 사건 발생 슬롯 스냅샷 아님. 과거 데이터 위 end-to-end replay-vs-chain 검증은 Geyser-backed 또는 ledger-replay account fetcher 가 필요; library 함수 (\`pool_state::compare_clmm_replay_to_archival\`, \`diff_attack_against_archival\`) 는 준비되어 있고 fetcher 구현이 미구현.
- **Token-2022 transfer fees** — parser 가 transfer-fee hook 을 회계하지 않음; hook 사용하는 mint 의 경우 \`SandwichAttack\` 에 기록된 \`amount_out\` 은 hook 적용 *전* 값.

## 5. 검증 방법론

세 layer, 각각 다른 버그 부류를 잡음.

### 5.1 Golden corpus + adversarial corpus

\`crates/eval/tests/{golden,adversarial}\` 가 큐레이션된 mainnet sandwich 의 manifest 를 박아 둠. Golden = 정통 positive; adversarial = 큐레이션된 negative (hop swap, MM activity, validator reorder) — 발화하면 *안 되는* 케이스. CI 가 둘 다 돌림; 어느 쪽이든 회귀하면 check 가 빨개짐.

### 5.2 Property-based 테스트

\`crates/pool-state/tests/k_invariant.rs\` 와 친구들이 \`proptest\` 로 random swap 입력에 대해 AMM 불변량을 assert (예: 수수료 적용 swap 후 \`x * y\` 단조; sqrt-price 가 입력 방향으로 이동). fixture 셋이 못 잡는 math-side 회귀를 잡음 — 특히 V3 sqrt-price primitive 의 i128 saturation 경계 edge case.

### 5.3 Real-mainnet capture as fixture

mainnet 에서 parser 버그가 surface 되면, fix 가 인라인 base64 인코딩된 mainnet fixture 를 회귀 테스트로 박아서 ship. v1.0.0 이 두 그런 케이스를 surface 함:

- **Pump.fun \`TradeEvent\` extended payload** (#35) — on-chain 프로그램이 backwards-compatible 업그레이드로 필드를 append, parser 의 \`data.len() == 113\` strict-equality 검사가 깨짐. 교훈: 외부 Anchor 이벤트를 디코딩하는 parser 는 길이에 strict equality 가 아닌 \`data.len() < MIN_PREFIX\` + 필드 모양 가드 사용. \`parses_real_mainnet_pump_fun_trade_event\` 에 fixture pin.
- **Raydium CLMM pool 계정 인덱스** (#37) — parser 가 \`accounts[1]\` (\`amm_config\` PDA, 117 byte, fee tier 별로 pool 들이 공유) 을 \`accounts[2]\` (\`pool_state\`, 1544 byte) 대신 가져와서, same-block detector 가 무관한 swap 들을 cross-mint "sandwich" 로 묶음. 올바른 인덱스 사용 + top-level / inner-CPI / 짧은 account list edge case 커버하는 unit test 4 개로 fix.

두 버그 모두 unit test 의 합성 입력이 parser 의 가정과 일치해서 unit test 를 통과함; mainnet capture 가 그걸 깨뜨림. 실제 바이트 (또는 CLMM 의 경우 실제 account 순서) 를 fixture 로 추가하는 게 다음에도 잡히게 만드는 방법. 새 parser 와 parser 변경은 최소 한 개의 mainnet-capture test 와 함께 ship 해야 함.

### 5.4 Mainnet 검증 실행

릴리스용으로, 1k–10k slot mainnet 윈도우에 binary 를 돌리고 DEX별 enrichment 매트릭스 검사. v1.0.0 두 hotfix 모두 이 방식으로 잡힘: 첫 번째는 Pump.fun TradeEvent breakage 를 노출한 1k 검증, 두 번째는 1k 표본이 놓친 빈도로 CLMM cross-mint false positive 를 노출한 10k 검증. "unit test 는 통과하는데 production 이 틀린" 상황의 정답은 더 큰 표본.

## 6. 어디를 봐야 하나

| 질문 | 파일 |
|---|---|
| Sandwich 가 어떻게 검출되나? | \`crates/detector-sameblock/src/detector.rs\`, \`crates/detector-window/src/pipeline.rs\` |
| DEX X 의 swap 은 어떻게 파싱되나? | \`crates/swap-events/src/dex/<x>.rs\` |
| DEX X 의 AMM-replay 수학? | \`crates/pool-state/src/<x>.rs\` |
| Evidence 가 carry 하는 신호는? | \`Signal\` enum in \`crates/swap-events/src/types.rs\` |
| Wire format / Vigil 계약? | \`crates/swap-events/schema/vigil-v1.json\` (canonical), \`contrib/vigil-types.ts\` (TS mirror) |
| 검증 harness? | \`crates/eval/tests/\`, \`crates/pool-state/tests/\` |
`;

export const rpcReadmeEn = `<p align="center">
  <h1 align="center">Vigil Protection RPC</h1>
  <p align="center">
    A Solana RPC proxy that shields swap transactions from sandwich attacks.<br/>
    Detects DEX swaps across 8 protocols, evaluates risk in real-time using a learned pool/attacker map, decodes instruction-level slippage, and routes risky transactions through Jito's private relay.
  </p>
</p>

<p align="center">
  <strong>English</strong> &middot;
  <a href="README.ko.md">한국어</a>
</p>

<p align="center">
  <img src="https://img.shields.io/badge/Rust-000000?style=for-the-badge&logo=rust&logoColor=white" alt="Rust" />
  <img src="https://img.shields.io/badge/Solana-9945FF?style=for-the-badge&logo=solana&logoColor=white" alt="Solana" />
  <img src="https://img.shields.io/badge/Axum-232323?style=for-the-badge&logo=rust&logoColor=white" alt="Axum" />
  <img src="https://img.shields.io/badge/Jito-FF6B35?style=for-the-badge" alt="Jito" />
  <img src="https://img.shields.io/badge/License-MIT-blue?style=for-the-badge" alt="MIT License" />
</p>

<p align="center">
  <a href="#how-it-works">How It Works</a> &middot;
  <a href="#quick-start">Quick Start</a> &middot;
  <a href="#configuration">Configuration</a> &middot;
  <a href="#supported-dexes">DEXes</a> &middot;
  <a href="#api">API</a> &middot;
  <a href="#architecture">Architecture</a>
</p>

---

Sandwich attacks are the most common MEV exploit on Solana. An attacker front-runs a victim's swap, moves the price, and back-runs to profit. **Vigil Protection RPC** sits between the user and the network, analyzing every \`sendTransaction\` in real-time and routing swap transactions through Jito's private relay to prevent mempool exposure.

> Detection primitive powered by [solana-sandwich-detector](https://github.com/SangHyeonKwon/solana-sandwich-detector). This repo is the **runtime protection layer** — detection stays upstream, protection lives here.

## How It Works

\`\`\`
                        sendTransaction
                              |
                    +---------v----------+
                    |   Swap Detection   |
                    |  (8 DEX programs)  |
                    +---------+----------+
                              |
                      swap?   |   not swap
                  +-----------+-----------+
                  |                       |
        +---------v----------+   +--------v--------+
        |  Slippage Decode   |   |   Direct RPC    |
        | (Raydium, Orca,    |   | (Helius staked) |
        |  Jupiter, Pump.fun)|   +---------+-------+
        +---------+----------+             |
                  |                        |
        +---------v----------+             |
        |   Risk Assessment  |             |
        | pool_score x slip  |             |
        | + attacker lookup  |             |
        +---------+----------+             |
                  |                        |
          +-------v--------+               |
          | Jito Relay     |--fail--+      |
          | (private send) |        |      |
          +-------+--------+        |      |
                  |             +---v------v---+
                  |             | Direct RPC   |
                  v             | (fallback)   |
               response        +------+-------+
                                      |
                                      v
                                   response

  [Background: Slot Watcher]
  Polls mainnet blocks --> extract_swaps --> detect_sandwiches
  --> updates Pool Risk Map + Attacker Set (in-memory LRU)
\`\`\`

### Decision matrix

| Condition | Route | Why |
|-----------|-------|-----|
| Not a swap | Direct RPC | No MEV risk |
| Swap, Jito enabled | Jito relay (fallback: Direct RPC) | Private mempool, no sandwich |
| Swap, Jito disabled | Direct RPC | User opted out of Jito |
| Swap, BLOCK + strict mode | JSON-RPC error | Hard reject high-risk TX |

## Quick Start

\`\`\`bash
# Clone & build
git clone https://github.com/EarthIsMine/Vigil-RPC.git
cd Vigil-RPC
cargo build --release

# Configure (copy and edit .env)
cp .env.example .env
# Set SOLANA_RPC_URL and SOLANA_SEND_TX_URL to your Helius endpoints

# Run
RUST_LOG=info cargo run --release

# Verify
curl http://localhost:8899/health
\`\`\`

Point your wallet or dApp at \`http://localhost:8899\` instead of the default Solana RPC. All JSON-RPC methods are proxied transparently; \`sendTransaction\` gets the protection layer.

## Supported DEXes

### Swap detection (8 protocols)

| DEX | Program ID | Pool index |
|-----|-----------|------------|
| Raydium V4 | \`675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8\` | accounts[1] |
| Raydium CLMM | \`CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK\` | accounts[2] |
| Raydium CPMM | \`CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C\` | accounts[3] |
| Orca Whirlpool | \`whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc\` | accounts[2] |
| Jupiter V6 | \`JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4\` | router (no single pool) |
| Meteora DLMM | \`LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo\` | accounts[0] |
| Pump.fun | \`6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P\` | accounts[2] |
| Phoenix | \`PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY\` | accounts[0] |

### Slippage decode (4 protocols)

| DEX | What's decoded | Unbounded signal |
|-----|---------------|-----------------|
| Raydium V4 | \`min_amount_out\` / \`max_amount_in\` from instruction data | \`min_out == 0\` or \`max_in == MAX\` |
| Orca Whirlpool | \`other_amount_threshold\` from Anchor swap | threshold == 0 (ExactIn) |
| Jupiter V6 | \`slippage_bps\` from last 3 bytes | bps > 500 (5%) |
| Pump.fun | \`max_sol_cost\` (buy) / \`min_sol_output\` (sell) | cost == MAX or output == 0 |

## Configuration

All configuration is via environment variables. A \`.env\` file is auto-loaded on startup.

| Variable | Default | Description |
|----------|---------|-------------|
| \`PROTECTION_RPC_PORT\` | \`8899\` | Server listen port |
| \`SOLANA_RPC_URL\` | \`https://api.mainnet-beta.solana.com\` | Upstream RPC for read queries + slot watcher |
| \`SOLANA_SEND_TX_URL\` | same as \`SOLANA_RPC_URL\` | Staked RPC for Direct sendTransaction |
| \`JITO_ENABLED\` | \`true\` | Route swap TXs through Jito relay |
| \`JITO_BLOCK_ENGINE_URL\` | \`https://mainnet.block-engine.jito.wtf\` | Jito Block Engine endpoint |
| \`BLOCK_MODE\` | \`permissive\` | \`permissive\` = log only, \`strict\` = reject BLOCK-level TXs |
| \`SLOT_POLL_INTERVAL_SECS\` | \`10\` | Slot watcher polling frequency |
| \`SLOT_WATCHER_LAG\` | \`32\` | Slots behind head to poll (finalization buffer) |
| \`POOL_LRU_CAPACITY\` | \`1024\` | Pool risk map LRU cache size |
| \`ATTACKER_LRU_CAPACITY\` | \`1024\` | Attacker set LRU cache size |
| \`POOL_TTL_SECS\` | \`86400\` | TTL before pool/attacker entries expire |
| \`RUST_LOG\` | - | Log level (\`info\`, \`debug\`, \`trace\`) |

## API

### \`GET /health\`

Returns server status, current block mode, and all metrics counters.

\`\`\`json
{
  "status": "ok",
  "block_mode": "Permissive",
  "metrics": {
    "risk_safe_total": 142,
    "risk_warn_total": 23,
    "risk_block_total": 5,
    "blocked_strict_total": 0,
    "forwarded_total": 1205,
    "jito_routed_total": 170,
    "slot_processed_total": 3400,
    "slot_failed_total": 12,
    "sandwich_detected_total": 8
  }
}
\`\`\`

### \`POST /\`

Standard Solana JSON-RPC proxy. All methods pass through transparently. \`sendTransaction\` gets the protection pipeline.

\`\`\`bash
# Regular RPC call (pass-through)
curl -X POST http://localhost:8899 \\
  -H "Content-Type: application/json" \\
  -d '{"jsonrpc":"2.0","id":1,"method":"getHealth"}'

# Protected sendTransaction
curl -X POST http://localhost:8899 \\
  -H "Content-Type: application/json" \\
  -d '{"jsonrpc":"2.0","id":1,"method":"sendTransaction","params":["BASE64_TX"]}'
\`\`\`

## Architecture

\`\`\`
src/
  main.rs                  Entry point, AppState init, slot watcher spawn
  config.rs                Env-based configuration (Jito, risk, polling)
  state.rs                 Shared state (Arc-wrapped senders, maps, metrics)
  error.rs                 JSON-RPC compatible error types
  metrics.rs               Atomic counters, /health snapshot

  analyzer/
    swap_detector.rs       DEX_LAYOUTS table, detect_swap, extract_pool_address
    tx_parser.rs           Base64/base58 → VersionedTransaction decode

  risk/
    pool_map.rs            PoolRiskMap — LRU + TTL, score from sandwich history
    attacker_set.rs        AttackerSet — known sandwich attacker signers
    decision.rs            assess() → SAFE / WARN / BLOCK
    slippage.rs            Instruction-level slippage decode (4 DEX families)

  slot_watcher/
    poller.rs              Background tokio task, getBlock → detect_sandwiches

  transmission/
    rpc_forward.rs         Direct RPC via solana-client
    jito_sender.rs         Jito Block Engine relay (sendTransaction + sendBundle)

  server/
    routes.rs              Axum router (/health, /)
    handlers/rpc.rs        sendTransaction interception + risk routing
    rpc_types.rs           JSON-RPC request/response types
\`\`\`

### Key dependency

[solana-sandwich-detector](https://github.com/SangHyeonKwon/solana-sandwich-detector) v1.0.1 provides:
- \`dex::all_parsers()\` — 8 DEX parsers
- \`dex::extract_swaps()\` — post-execution swap extraction (slot watcher)
- \`detector::detect_sandwiches()\` — same-block pattern matching
- \`parser::parse_block()\` — RPC block → internal BlockData

## Tests

\`\`\`bash
cargo test                    # All 25 tests
cargo test risk_pipeline      # Risk assessment pipeline (8 tests)
cargo test http_integration   # HTTP handler tests (3 tests)
cargo test slippage           # Slippage decode tests (7 tests)
\`\`\`

## License

MIT
`;

export const rpcReadmeKo = `<p align="center">
  <h1 align="center">Vigil Protection RPC</h1>
  <p align="center">
    스왑 트랜잭션을 샌드위치 공격으로부터 보호하는 Solana RPC 프록시.<br/>
    8개 DEX 프로토콜의 스왑을 감지하고, 학습된 풀/공격자 맵으로 실시간 위험도를 평가하며, instruction 수준의 슬리피지를 디코드하고, 위험한 트랜잭션을 Jito 프라이빗 릴레이로 라우팅합니다.
  </p>
</p>

<p align="center">
  <a href="README.md">English</a> &middot;
  <strong>한국어</strong>
</p>

<p align="center">
  <img src="https://img.shields.io/badge/Rust-000000?style=for-the-badge&logo=rust&logoColor=white" alt="Rust" />
  <img src="https://img.shields.io/badge/Solana-9945FF?style=for-the-badge&logo=solana&logoColor=white" alt="Solana" />
  <img src="https://img.shields.io/badge/Axum-232323?style=for-the-badge&logo=rust&logoColor=white" alt="Axum" />
  <img src="https://img.shields.io/badge/Jito-FF6B35?style=for-the-badge" alt="Jito" />
  <img src="https://img.shields.io/badge/License-MIT-blue?style=for-the-badge" alt="MIT License" />
</p>

<p align="center">
  <a href="#동작-원리">동작 원리</a> &middot;
  <a href="#빠른-시작">빠른 시작</a> &middot;
  <a href="#설정">설정</a> &middot;
  <a href="#지원-dex">DEX</a> &middot;
  <a href="#api">API</a> &middot;
  <a href="#아키텍처">아키텍처</a>
</p>

---

샌드위치 공격은 Solana에서 가장 흔한 MEV 착취 방식입니다. 공격자가 피해자의 스왑을 선행매매(front-run)하여 가격을 움직인 후, 후행매매(back-run)로 이익을 취합니다. **Vigil Protection RPC**는 사용자와 네트워크 사이에 위치하여 모든 \`sendTransaction\`을 실시간으로 분석하고, 스왑 트랜잭션을 Jito 프라이빗 릴레이를 통해 전송하여 멤풀 노출을 방지합니다.

> 탐지 엔진: [solana-sandwich-detector](https://github.com/SangHyeonKwon/solana-sandwich-detector). 이 레포는 **런타임 보호 레이어**입니다 — 탐지는 upstream에, 보호는 여기에.

## 동작 원리

\`\`\`
                        sendTransaction
                              |
                    +---------v----------+
                    |    스왑 감지        |
                    |  (8개 DEX 프로그램) |
                    +---------+----------+
                              |
                     스왑?    |   스왑 아님
                  +-----------+-----------+
                  |                       |
        +---------v----------+   +--------v--------+
        |  슬리피지 디코드    |   |   Direct RPC    |
        | (Raydium, Orca,    |   | (Helius staked) |
        |  Jupiter, Pump.fun)|   +---------+-------+
        +---------+----------+             |
                  |                        |
        +---------v----------+             |
        |    위험도 평가      |             |
        | pool_score x slip  |             |
        | + 공격자 조회       |             |
        +---------+----------+             |
                  |                        |
          +-------v--------+               |
          | Jito 릴레이    |--실패--+      |
          | (프라이빗 전송) |        |      |
          +-------+--------+        |      |
                  |             +---v------v---+
                  |             | Direct RPC   |
                  v             | (폴백)       |
               응답             +------+-------+
                                      |
                                      v
                                    응답

  [백그라운드: 슬롯 워처]
  메인넷 블록 폴링 --> extract_swaps --> detect_sandwiches
  --> Pool Risk Map + Attacker Set 갱신 (인메모리 LRU)
\`\`\`

### 결정 매트릭스

| 조건 | 라우팅 | 이유 |
|------|--------|------|
| 스왑 아님 | Direct RPC | MEV 위험 없음 |
| 스왑, Jito 활성화 | Jito 릴레이 (실패 시 Direct RPC 폴백) | 프라이빗 멤풀, 샌드위치 불가 |
| 스왑, Jito 비활성화 | Direct RPC | 사용자가 Jito 비활성화 |
| 스왑, BLOCK + strict 모드 | JSON-RPC 에러 | 고위험 TX 거부 |

## 빠른 시작

\`\`\`bash
# 클론 & 빌드
git clone https://github.com/EarthIsMine/Vigil-RPC.git
cd Vigil-RPC
cargo build --release

# 설정 (.env 복사 후 편집)
cp .env.example .env
# SOLANA_RPC_URL과 SOLANA_SEND_TX_URL에 Helius 엔드포인트 설정

# 실행
RUST_LOG=info cargo run --release

# 확인
curl http://localhost:8899/health
\`\`\`

지갑이나 dApp의 RPC를 \`http://localhost:8899\`로 변경하면 됩니다. 모든 JSON-RPC 메서드는 투명하게 프록시되고, \`sendTransaction\`만 보호 파이프라인을 거칩니다.

## 지원 DEX

### 스왑 감지 (8개 프로토콜)

| DEX | Program ID | Pool 인덱스 |
|-----|-----------|------------|
| Raydium V4 | \`675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8\` | accounts[1] |
| Raydium CLMM | \`CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK\` | accounts[2] |
| Raydium CPMM | \`CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C\` | accounts[3] |
| Orca Whirlpool | \`whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc\` | accounts[2] |
| Jupiter V6 | \`JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4\` | 라우터 (단일 풀 없음) |
| Meteora DLMM | \`LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo\` | accounts[0] |
| Pump.fun | \`6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P\` | accounts[2] |
| Phoenix | \`PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY\` | accounts[0] |

### 슬리피지 디코드 (4개 프로토콜)

| DEX | 디코드 대상 | 무제한 슬리피지 신호 |
|-----|------------|---------------------|
| Raydium V4 | instruction data의 \`min_amount_out\` / \`max_amount_in\` | \`min_out == 0\` 또는 \`max_in == MAX\` |
| Orca Whirlpool | Anchor swap의 \`other_amount_threshold\` | threshold == 0 (ExactIn) |
| Jupiter V6 | 마지막 3바이트의 \`slippage_bps\` | bps > 500 (5%) |
| Pump.fun | \`max_sol_cost\` (매수) / \`min_sol_output\` (매도) | cost == MAX 또는 output == 0 |

## 설정

모든 설정은 환경변수로 관리됩니다. \`.env\` 파일은 서버 시작 시 자동으로 로드됩니다.

| 변수 | 기본값 | 설명 |
|------|--------|------|
| \`PROTECTION_RPC_PORT\` | \`8899\` | 서버 리스닝 포트 |
| \`SOLANA_RPC_URL\` | \`https://api.mainnet-beta.solana.com\` | 읽기 쿼리 + 슬롯 워처용 업스트림 RPC |
| \`SOLANA_SEND_TX_URL\` | \`SOLANA_RPC_URL\`과 동일 | sendTransaction용 Staked RPC |
| \`JITO_ENABLED\` | \`true\` | 스왑 TX를 Jito 릴레이로 라우팅 |
| \`JITO_BLOCK_ENGINE_URL\` | \`https://mainnet.block-engine.jito.wtf\` | Jito Block Engine 엔드포인트 |
| \`BLOCK_MODE\` | \`permissive\` | \`permissive\` = 로그만, \`strict\` = BLOCK 수준 TX 거부 |
| \`SLOT_POLL_INTERVAL_SECS\` | \`10\` | 슬롯 워처 폴링 주기(초) |
| \`SLOT_WATCHER_LAG\` | \`32\` | 폴링 시 헤드 대비 지연 슬롯 수 |
| \`POOL_LRU_CAPACITY\` | \`1024\` | Pool Risk Map LRU 캐시 크기 |
| \`ATTACKER_LRU_CAPACITY\` | \`1024\` | Attacker Set LRU 캐시 크기 |
| \`POOL_TTL_SECS\` | \`86400\` | 풀/공격자 항목 TTL(초) |
| \`RUST_LOG\` | - | 로그 레벨 (\`info\`, \`debug\`, \`trace\`) |

## API

### \`GET /health\`

서버 상태, 현재 블록 모드, 전체 메트릭 카운터를 반환합니다.

\`\`\`json
{
  "status": "ok",
  "block_mode": "Permissive",
  "metrics": {
    "risk_safe_total": 142,
    "risk_warn_total": 23,
    "risk_block_total": 5,
    "blocked_strict_total": 0,
    "forwarded_total": 1205,
    "jito_routed_total": 170,
    "slot_processed_total": 3400,
    "slot_failed_total": 12,
    "sandwich_detected_total": 8
  }
}
\`\`\`

### \`POST /\`

표준 Solana JSON-RPC 프록시. 모든 메서드는 투명하게 패스스루됩니다. \`sendTransaction\`만 보호 파이프라인을 거칩니다.

\`\`\`bash
# 일반 RPC 호출 (패스스루)
curl -X POST http://localhost:8899 \\
  -H "Content-Type: application/json" \\
  -d '{"jsonrpc":"2.0","id":1,"method":"getHealth"}'

# 보호된 sendTransaction
curl -X POST http://localhost:8899 \\
  -H "Content-Type: application/json" \\
  -d '{"jsonrpc":"2.0","id":1,"method":"sendTransaction","params":["BASE64_TX"]}'
\`\`\`

## 아키텍처

\`\`\`
src/
  main.rs                  진입점, AppState 초기화, 슬롯 워처 spawn
  config.rs                환경변수 기반 설정 (Jito, risk, polling)
  state.rs                 공유 상태 (Arc 래핑된 sender, map, metrics)
  error.rs                 JSON-RPC 호환 에러 타입
  metrics.rs               Atomic 카운터, /health 스냅샷

  analyzer/
    swap_detector.rs       DEX_LAYOUTS 테이블, detect_swap, extract_pool_address
    tx_parser.rs           Base64/base58 → VersionedTransaction 디코드

  risk/
    pool_map.rs            PoolRiskMap — LRU + TTL, 샌드위치 이력 기반 점수
    attacker_set.rs        AttackerSet — 알려진 샌드위치 공격자 signer
    decision.rs            assess() → SAFE / WARN / BLOCK
    slippage.rs            Instruction 수준 슬리피지 디코드 (4개 DEX 패밀리)

  slot_watcher/
    poller.rs              백그라운드 tokio 태스크, getBlock → detect_sandwiches

  transmission/
    rpc_forward.rs         solana-client 기반 Direct RPC
    jito_sender.rs         Jito Block Engine 릴레이 (sendTransaction + sendBundle)

  server/
    routes.rs              Axum 라우터 (/health, /)
    handlers/rpc.rs        sendTransaction 인터셉트 + 위험도 기반 라우팅
    rpc_types.rs           JSON-RPC 요청/응답 타입
\`\`\`

### 핵심 의존성

[solana-sandwich-detector](https://github.com/SangHyeonKwon/solana-sandwich-detector) v1.0.1:
- \`dex::all_parsers()\` — 8개 DEX 파서
- \`dex::extract_swaps()\` — 실행 후 스왑 추출 (슬롯 워처 전용)
- \`detector::detect_sandwiches()\` — 동일 블록 패턴 매칭
- \`parser::parse_block()\` — RPC 블록 → 내부 BlockData

## 테스트

\`\`\`bash
cargo test                    # 전체 25개 테스트
cargo test risk_pipeline      # 위험도 평가 파이프라인 (8개)
cargo test http_integration   # HTTP 핸들러 (3개)
cargo test slippage           # 슬리피지 디코드 (7개)
\`\`\`

## 라이선스

MIT
`;
